apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: customer-app
  labels:
    app: mongodb
    tier: database
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongodb
  selector:
    app: mongodb
    tier: database